project:
  type: website

website:
  title: "Survival Analysis of Acute Myeloid Leukemia (AML) Patients"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - about.qmd
    

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



